name: API Tests with Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install robotframework robotframework-requests robotframework-jsonlibrary allure-robotframework

      - name: Run API Tests with Allure
        run: |
          robot --listener allure_robotframework -d results tests/rijksmuseum_tests.robot

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: results
          allure_history: allure-history

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
